spring.application.name=ads-service
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/ads_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/ProlanceRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/ProlanceRealm/protocol/openid-connect/certs

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
